version: '3'
services:
  frontend:
    image: production-fullstack-frontend
    build:
      context: ./frontend # Use the current directory as the build context
      dockerfile: Dockerfile # Use the Dockerfile defined above
    volumes:
      - /app/node_modules
      - ./frontend:/app

  backend:
    image: backend
    build:
      context: ./backend # Path to the backend code
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "3001:3001"
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
