name: Transfer Files to Azure VM

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an appropriate runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2


    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script:  ls -a

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
        if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      
    - name: rsync over SSH
      run: rsync -r . ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/${{ secrets.USERNAME }}/app/




